window.CONTAINER_LED_TELAS = Object.freeze([
  Object.freeze({
    id: 1,
    slug: "rondon-pacheco",
    nome: "Rondon Pacheco",
    tipo: "Outdoor",
    endereco: "Av. Rondon Pacheco, 2064",
    bairro: "Vigilato Pereira",
    cidade: "Uberlândia",
    estado: "MG",
    largura: 1,
    altura: 7,
    status: "Em operação",
    imagem: "/assets/painel-rondon.webp",
    imagemAlt: "Tela digital Container LED na Avenida Rondon Pacheco",
    googleMaps: "https://www.google.com/maps/search/?api=1&query=Av.%20Rondon%20Pacheco%2C%202064%2C%20Uberl%C3%A2ndia%2C%20MG",
    mapaEmbed: "https://www.google.com/maps?q=Av.%20Rondon%20Pacheco%2C%202064%2C%20Uberl%C3%A2ndia%2C%20MG&output=embed",
    audiencia: "9,2 mi/mês",
    insercoes: "~360/dia · ~10.800/mês",
    formatoExibicao: "Loop contínuo",
    duracao: "10s por inserção · ~3.600 s/dia · ~108.000 s/mês",
    resolucao: "1080×1920 px · 9:16",
    formatosAceitos: "JPG ou PNG (foto) · MP4 ou MOV (vídeo)",
    descricao: "Na principal avenida de Uberlândia, ao lado do Colégio Gabarito e Griff Shopping, com amplo campo visual e fluxo intenso."
  }),
  Object.freeze({
    id: 2,
    slug: "anselmo-alves",
    nome: "Anselmo Alves dos Santos — Pátio Sabiá",
    tipo: "Outdoor",
    endereco: "Av. Anselmo Alves dos Santos, 1056",
    bairro: "Santa Mônica",
    cidade: "Uberlândia",
    estado: "MG",
    largura: 2,
    altura: 4,
    status: "Em operação",
    imagem: "/assets/painel-anselmo-alves.webp",
    imagemAlt: "Tela digital Container LED na Avenida Anselmo Alves dos Santos em frente ao Pátio Sabiá",
    googleMaps: "https://www.google.com/maps/search/?api=1&query=Av.%20Anselmo%20Alves%20dos%20Santos%2C%201056%2C%20Uberl%C3%A2ndia%2C%20MG",
    mapaEmbed: "https://www.google.com/maps?q=Av.%20Anselmo%20Alves%20dos%20Santos%2C%201056%2C%20Uberl%C3%A2ndia%2C%20MG&z=13&output=embed",
    audiencia: "4,65 mi/mês",
    insercoes: "~360/dia · ~10.800/mês",
    formatoExibicao: "Loop contínuo",
    duracao: "10s por inserção · ~3.600 s/dia · ~108.000 s/mês",
    resolucao: "1080×1920 px · 9:16",
    formatosAceitos: "JPG ou PNG (foto) · MP4 ou MOV (vídeo)",
    descricao: "Em frente ao Pátio Sabiá, em uma região de alto fluxo que conecta importantes setores de Uberlândia, a 200 metros do Parque do Sabiá."
  }),
  Object.freeze({
    id: 3,
    slug: "terminal-central",
    nome: "Terminal Central",
    tipo: "Totem",
    variante: "Full",
    endereco: "Av. João Pinheiro, 1154",
    bairro: "Centro",
    cidade: "Uberlândia",
    estado: "MG",
    local: "Terminal Central — Centro — Uberlândia/MG",
    largura: 1,
    altura: 2,
    status: "EM BREVE",
    imagem: "/assets/tela-03-terminal-central.webp",
    imagemAlt: "Totem digital Container LED na K-Fé Container, dentro do Terminal Central",
    googleMaps: "https://maps.app.goo.gl/rVtDsu9JGKjDJ9Yy6",
    mapaEmbed: "https://www.google.com/maps?q=-18.9140061,-48.2761088&output=embed",
    audiencia: "3,5 mi/mês",
    insercoes: "~360/dia · ~10.800/mês",
    formatoExibicao: "Loop contínuo",
    duracao: "10s por inserção · ~3.600 s/dia · ~108.000 s/mês",
    resolucao: "1080×1920 px · 9:16",
    formatosAceitos: "JPG ou PNG (foto) · MP4 ou MOV (vídeo)",
    descricao: "Cruzamento Av. João Pessoa / Av. João Pinheiro, 1154. Tela localizada no ponto de parada de motoristas de aplicativos (Uber), ao lado da escada rolante do Terminal Central, dentro da cafeteria K-Fé Container."
  }),
  Object.freeze({
    id: 4,
    slug: "container-barber-club-santa-monica",
    nome: "Container Barber Club — Santa Mônica",
    tipo: "Totem",
    variante: "Full",
    endereco: "Av. Belarmino Cotta Pacheco / R. Nordau Gonçalves de Melo (antiga 14)",
    bairro: "Santa Mônica",
    cidade: "Uberlândia",
    estado: "MG",
    local: "Sinaleiro/cruzamento da Av. Belarmino Cotta Pacheco com a Rua Nordau Gonçalves de Melo (antiga Rua 14), bairro Santa Mônica - Barbearia Container Barber Club",
    largura: 1,
    altura: 2,
    status: "Em operação",
    imagem: "/assets/tela-04-container-barber-club.webp",
    imagemAlt: "Totem digital Container LED, tela Full de 2,0 x 1,0 m",
    googleMaps: "https://www.google.com/maps/place/Av.+Belarmino+Cotta+Pacheco,+1177+-+Santa+M%C3%B4nica,+Uberl%C3%A2ndia+-+MG,+38408-168/@-18.9166353,-48.247639,21z/data=!4m6!3m5!1s0x94a445798be6f507:0x7a9f607ab20619b8!8m2!3d-18.9166607!4d-48.2477827!16s%2Fg%2F11kqfy8z94",
    mapaEmbed: "https://www.google.com/maps?q=-18.9166607,-48.2477827&output=embed",
    audiencia: "2,0 mi/mês",
    insercoes: "~360/dia · ~10.800/mês",
    formatoExibicao: "Loop contínuo",
    duracao: "10s por inserção · ~3.600 s/dia · ~108.000 s/mês",
    resolucao: "1080×1920 px · 9:16",
    formatosAceitos: "JPG ou PNG (foto) · MP4 ou MOV (vídeo)",
    descricao: "Totem digital na Container Barber Club, no cruzamento da Av. Belarmino Cotta Pacheco com a Rua Nordau Gonçalves de Melo (antiga Rua 14), no bairro Santa Mônica."
  }),
  Object.freeze({
    id: 5,
    slug: "tela-05",
    nome: "Em breve",
    tipo: "Totem",
    endereco: "",
    bairro: "",
    cidade: "Uberlândia",
    estado: "MG",
    largura: null,
    altura: null,
    status: "EM BREVE",
    imagem: "/assets/tela-em-breve.webp",
    imagemAlt: "Totem digital Container LED — ponto em breve",
    googleMaps: "",
    mapaEmbed: "",
    audiencia: "72 mil/mês",
    insercoes: "~360/dia · ~10.800/mês",
    formatoExibicao: "Loop contínuo",
    duracao: "10s por inserção · ~3.600 s/dia · ~108.000 s/mês",
    resolucao: "1080×1920 px · 9:16",
    formatosAceitos: "JPG ou PNG (foto) · MP4 ou MOV (vídeo)",
    descricao: "Detalhes deste ponto serão publicados assim que o endereço for confirmado."
  }),
  Object.freeze({
    id: 6,
    slug: "tela-06",
    nome: "Em breve",
    tipo: "Totem",
    endereco: "",
    bairro: "",
    cidade: "Uberlândia",
    estado: "MG",
    largura: null,
    altura: null,
    status: "EM BREVE",
    imagem: "/assets/tela-em-breve.webp",
    imagemAlt: "Totem digital Container LED — ponto em breve",
    googleMaps: "",
    mapaEmbed: "",
    audiencia: "72 mil/mês",
    insercoes: "~360/dia · ~10.800/mês",
    formatoExibicao: "Loop contínuo",
    duracao: "10s por inserção · ~3.600 s/dia · ~108.000 s/mês",
    resolucao: "1080×1920 px · 9:16",
    formatosAceitos: "JPG ou PNG (foto) · MP4 ou MOV (vídeo)",
    descricao: "Detalhes deste ponto serão publicados assim que o endereço for confirmado."
  })
]);
